### ISSUE TITLE
Drop namespace support

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/translate.js#14]
@maranomynet I just thought if we can drop namespace support.

I do it the following way

```
// define translation
messages = {
  'foo.bar.baz': 'forbarbaz'
}

// usage
t('foo.bar.baz')
```

I think it can do all thing you can do with namespaces. It would simplify and for sure fasten the computation of the translation.

What do you think?

**Comment by StephanHoyer** [comment]
I find it also simpler in terms of maintenance since you can find unused translations more easily by matching the stings.

**Comment by StephanHoyer** [comment]
an other option would be to flatten the messages object during initialisation.

**Comment by StephanHoyer** [comment]
@maranomynet would you mind reviewing my pr and annotate or merge it.

**Comment by StephanHoyer** [comment]
this way you can also uglify your translation-keys with `-d` and `-define-from-module` option of uglify.js. Haven't tested though

**Comment by maranomynet** [comment]
Is it ok if I take a look at this later today or tomorrow morning.

I'm inclined to like this because it makes things faster and quite a bit simpler.

The main use-case I see for supporting namespaces, is that it makes composing large translation objects somewhat easier.

**Comment by maranomynet** [comment]
I might have been too hasty npm publishing 0.3.0 just now, but #16 won't have any functional differences, so it can wait until the next release anyway.
