### ISSUE TITLE
Add vdom awarness

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/translate.js#19]
Would be great to allow something like this
```javascript
t = translate({
  foo: 'bar {baz} foz'
})

t('foo', {
  baz: m('img', {}) //
})
// result: ['bar ', m('img', {}), ' foz']
```

@maranomynet what do you think of that?

**Comment by maranomynet** [comment]
Although I truly see the benefit, this feels like feature-creep and breaks the expectation of the translate function always returning a string.

could this be added as an off-by-default option - or should we make this possible by allowing users to supply a custom `assemble` fuction?

**Comment by StephanHoyer** [comment]
yeah, this should definitely not the default case. `assemble` would be an option. Or one could provide a special handler
```javascript
t.inParts('foo', {
  baz: m('img', {})
})
```
Name is odd though.

Implementing this would be pretty easy if we replace the while loop by for-loop
```javascript
    for (var i=1; i < len; i+=2) {
      var val = replacements[parts[i]]
      if (val == null) {
        if (parts[i] === 'n' && count != null) {
          val = count
        } else {
          debug && console.warn('No "' + parts[i] + '" in placeholder object:', replacements)
          val = '{' + parts[i] + '}'
        }
      }
      parts[i] = val;
    }
    return parts; // or parts.join('') in default case
```
