### ISSUE TITLE
Plural forms and JSON

### ISSUE THREAD

**Issue by Spone** [StephanHoyer/translate.js#28]
Hello,

I'm storing my translations in a JSON file that is loaded and passed to the `translate` function.
I cannot use the pluralization feature because JSON standard allows only double quoted string as property key.

Is there a way to fix it?
Thanks in advance

**Comment by maranomynet** [comment]
Hmm... I'm not sure I understand what your problem is.

Could you provide us with a failing test to work on?

(i.e. either via codepen/jsfiddle/etc. or, preferably, adding it to [tests.js](https://github.com/StephanHoyer/translate.js/blob/master/test.js) and making a pull request.)

**Comment by Spone** [comment]
So I started working on a test case and realized the problem was not using JSON file but assuming that I can use the "namespace" notation for pluralization.

Here is what I was trying to achieve: https://github.com/Spone/translate.js/commit/1aa95d4e77ddff136c2c53892e2e7472b47e7a28

Can this library support this use? I can make a PR.

**Comment by maranomynet** [comment]
I see. This notation is not supported, and the "namespace" notation was dropped as of version 0.3 to keep things as fast and simple as possible.

My first instinct is to hesitate adding it back in for this special case. But I'll think about it.

My suggestion would be to pre-process the JSON to map these name-spaced keys to an object, before using it to seed the translation function.

If you decide to fork the library and implement this feature in your repo, please make a PR and we'll look at it.

**Comment by StephanHoyer** [comment]
I think that wasn't the namespace notation we dropped. But I think it may be a valid way to define plural translations. If we find an easy way to support this I'm in.

**Comment by maranomynet** [comment]
You're right. This is different.

This notation itself is fairly easy to support, but requires double-checking in several places. Translations with `count`/`subKey` (as in #27) will become slightly slower to resolve, but not by much.

However, It's worth noting that adding this feature adds ambiguity, as the key 'foo.1' can now be matched as a result for both `t('foo',1)` and `t('foo.1')`, which may lead to surprising results.

We also need to document how to handle cases where both `'foo':{1:'bar'}` and `'foo.1':'bar'` exist.

And we need to document how we deal with cases where both `'foo':'bar'` and `'foo.1':'bar'` exist.

This also calls for the inevitable feature-request of having the `.` delimiter configurable.

**Comment by Spone** [comment]
Thanks for your quick replies!

@maranomynet I think you summed up the problem accurately.
Considering the drawbacks, I'm wondering if it's a good idea to implement this...

**Comment by maranomynet** [comment]
We could support this without making things too ambiguous/complex by making the user specify which pluralization/subkey formatting to use at the time of initialization.

The old behaviour would be default, but passing a `flatKeys: true` setting (and optionally `subkeyDelmiter:'--'`) would make the pluralization/subkey resolution go down a separate internal codepath.

**Comment by StephanHoyer** [comment]
@maranomynet I oversaw this issue. Thanks for pointing this out.
@Spone: If it's not a big of a deal, you might try to change the way you manage plural forms so it matches the required notation. Alternativly you can parse your translation strings so they match.

If this is no options for you you might simply roll you own fork of this project. Code-base is fairly simple and also pretty stable right now.

**Comment by Spone** [comment]
Thanks for your help, I finally changed the structure of my file.
