### ISSUE TITLE
l16n helper

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/translate.js#29]
I think about integration of my l16n helper into this lib. It builds on top of translate.js so maybe it's worth thinking about this.

It currently only handles dates. Times, Numbers and Currencies might be things to consider. It also has no parser functionality atm.

@maranomynet what do you think? How do you handle this in your app?

**Comment by maranomynet** [comment]
So far I've not been forced to handle number-formatting.

Dates I've done with replacement tokens, i.e. `"{wday}, {month} {date}."` and nested calls.

**Comment by maranomynet** [comment]
Currencies could be done much the same way, and same goes for quotation-marks...

```js
  "price": "{price}{currency}",
  "quote": "«{text}»",
```

It's a bit icky, but would work.

What's your approach?

**Comment by StephanHoyer** [comment]
That's basically what I have.
```
'use strict';

var t = require('./translate');

function padZero(number) {
  if (number < 10) {
    return '0' + number;
  }
  return number;
}

module.exports = {
  date: {
    YMD: function(date) {
      date = new Date(date);
      return t('date.formatdaymonthyear', {
        year: date.getFullYear(),
        month: padZero(date.getMonth() + 1),
        day: padZero(date.getDate())
      });
    },
    YMDHI: function(date) {
      date = new Date(date);
      return t('date.formatdaymonthyearwithtime', {
        year: date.getFullYear(),
        month: padZero(date.getMonth() + 1),
        day: padZero(date.getDate()),
        hour: padZero(date.getHours()),
        minute: padZero(date.getMinutes())
      });
    }
  }
};
```

I think we don't need more for this. Numbers is a little trickier though (e. G. `1.000.000,000` vs `1,000,000.000`). This does not necessarily have to be includes here.

As I think about it maybe it's enough to create a few examples for this in the wiki.
