### ISSUE TITLE
Multiple pluralisation in one translation

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/translate.js#34]
```js
var t = translate({
  key: {
    1: {
      1: '1 {foo}  1 foz',
      n: '1 {foo}  {n} fozes'
    },
    n: {
      1: 'n {foo}s  1 foz',
      n: 'n {foo}s {n} fozes'
    } 
  }
});

t('key', 3, 4, { foo: 'bar' }) === '3 bars 4 fozes'
```

**Comment by maranomynet** [comment]
I assume you meant for the `n` object to be something like this...

    n: {
      1: '{n} {foo}s  1 foz',
      n: '{n} {foo}s {n} fozes'
    } 

...which begs the question how should the translation function know which count goes into which `{n}` slot?

Seems like a highly specialized feature that's hard to add to the core function without bloating and slowing it dow, and hard to document clearly.

I also wonder if in most cases a simpler, more straightforward usage of the current feature set would be sufficient:

```js
var t = translate({
  key: {
    1: '1 {foo}',
    1: '{n} {foo}s'
  },
  key2: {
    1: '1 foz',
    n: '{n} fozes'
  }
});

t('key', 3, { foo: 'bar' }) +' '+ t('key2', 4) // =>  '3 bars 4 fozes'
```

**Comment by maranomynet** [comment]
...or even

```js
var t = translate({
  key: {
    1: '1 {foo} {foz}',
    n: '{n} {foo}s {foz}'
  },
  foz: {
    1: '1 foz',
    n: '{n} fozes'
  }
});

t('key', 3, { foo: 'bar', foz: t('foz',4) })  // =>  '3 bars 4 fozes'
```

**Comment by StephanHoyer** [comment]
Yeah, that's how we do it currently. But it's not as flexible as it needs to. But you're right. Adds to much complexity. Alternative workaround would be something like

```
t('keyFooCount' + pluralize(countFoo), countBars, { foo: 'bar' })
```
