### ISSUE TITLE
support curryish calling

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/translate.js#35]
like so

```
t('foo.bar.')('baz') === t('foo.bar.baz');
```

@maranomynet Opinions?

**Comment by maranomynet** [comment]
Hmm... seems easy enough to implement as a standalone factory function.

```js
t.prefix = (prefix) => function(suffix){
  return t.apply(t, [prefix+suffix].concat([].slice.call(arguments));
}

t.prefix('foo.bar.')('baz');
```

Not sure if this is common enough use-case to be part of the core module, with the added documentation, etc, even though it's tiny in size.

**Comment by StephanHoyer** [comment]
I will try that first. Will come back to it, if this is usable. Otherwise I will close this.

**Comment by maranomynet** [comment]
```js
t.prefix = (prefix) => function(){
  const args = [].slice.call(arguments);
  args[0] = prefix+args[0];
  return t.apply(t, args);
}

t.prefix('foo.bar.')('baz');
```

**Comment by maranomynet** [comment]
Closing for now, feel free to reopen if needed.
