### ISSUE TITLE
support `gt` syntax like musterknabe's version

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/translate.js#36]
see https://github.com/musterknabe/translate.js/commit/9f9bc773e117ccdb6130845a51f304dd0ab3c2b1

Good idea? Might have some performance implications

**Comment by StephanHoyer** [comment]
maybe it's not scope of this module. I currently do this with something like

```js
var t = translate({
  someKey: {
    0: 'nothing',
    1: 'one thing',
    100: 'Insane amount of things',
    n: '{n} things'
  }
}
t('someKey', Math.min(100, x))
```

**Comment by maranomynet** [comment]
Yeah, I'd seen that feature, but as you say it's borderline out of scope, has limited value and seems difficult to implement without impacting performance or adding IMO too much bloat.
