### ISSUE TITLE
Arrow functions and IE11

### ISSUE THREAD

**Issue by angelozehr** [StephanHoyer/translate.js#47]
Thx for your helpful library, we love it! And we'd love to continue using it but since version [1.0.0](https://github.com/StephanHoyer/translate.js/blob/master/CHANGELOG.md#100) our React App won't render anymore in IE11 (still accounting for 10-20% of our visitors).

That's because in your `index.js`, that we import, you have some ES6 sugar, like arrow functions etc.

We use webpack to bundle our code and the file is thus bundled and shipped with these arrow functions, which in Internet Explorer 11 causes a `SCRIPT1002: Syntax error` and everything crashes.

In this [discussion](https://stackoverflow.com/questions/47672324/script1002-syntax-error-in-ie11-with-react-babel-webpack?rq=1), someone recommends taking the file from the node_modules folder and transpiling it, but honestly, I don't think this is the best way to solve this.

Would it be an option for you to transpile your code again so we can just import it?

**Comment by maranomynet** [comment]
@angelozehr Just to make sure I understand correctly: You're using WebPack for bundling, but without any plugins (like Babel, or [Bublé](https://www.npmjs.com/package/buble-loader)) for transpilation. Right?

@StephanHoyer this would mean adding back `rollup-plugin-buble` into the build script. I see no harm in that.

**Comment by maranomynet** [comment]
@angelozehr BTW, the fact you're bundling, means you're already "transpiling", sort of, so adding a super-fast es6 transpiler like Bublé is just a tiny step further down the slippery slope you've already started down. 😉 

And you're likely to run into this more and more going into the future.

**Comment by maranomynet** [comment]
You're right, node_modules should be assumed to be pre-transpiled to a baseline syntax. Most transpilers are designed to work per-module and will skip node_modules by default.

I lean towards classifying this as a bug.

**Comment by maranomynet** [comment]
@angelozehr v1.1.1 is out.

**Comment by angelozehr** [comment]
Thank you a lot!

**Comment by angelozehr** [comment]
https://github.com/StephanHoyer/translate.js/blob/6450b90cf49128aad99979c0ac53f18b9106faa2/src/index.js#L1

The same problem appears again after this isObject function has been introduced
