### ISSUE TITLE
Kick out Greenkeeper as contributor?

### ISSUE THREAD

**Issue by maranomynet** [StephanHoyer/translate.js#73]
@StephanHoyer I really don't see the value of Mr. Greenkeeper creating noise for this repo, and sprouting endless PRs every time a *development* dependency has a minor update. 

Updating devDependencies by hand, whenever we happen to actually work on the code, is zero hassle, and even if we were to miss a patch release or two of `onchange` or `rollup` our build is not likely to spontaneously burst into flames.

However, keeping Greenkeeper onboard evidently leads to accidental zero-value releases like [1.2.1](https://github.com/StephanHoyer/translate.js/blob/master/CHANGELOG.md#121) and [1.1.2](https://github.com/StephanHoyer/translate.js/blob/master/CHANGELOG.md#112).

**Comment by StephanHoyer** [comment]
Make it so!

**Comment by maranomynet** [comment]
You realize that I don't have access to manage collaborators, right?

https://github.com/StephanHoyer/translate.js/pull/80

**Comment by maranomynet** [comment]
I just deleted close to 150 zero-value branches created by Greenkeeper.
Could you please remove him/it from the collaborators list?

**Comment by maranomynet** [comment]
...or come to think of it, you must have kicked it already.
I haven't noticed any PRs lately, so those might just have been leftover branches.

Right?

**Comment by StephanHoyer** [comment]
Seems so.  I just checked integrations and colabs. No sign of greenkeeper anymore.

Thanks for the latest fixes and the cleanup.
