### ISSUE TITLE
Script error (when using new Babel setup)

### ISSUE THREAD

**Issue by Foundasys** [StephanHoyer/translate.js#78]
With v0.7.0 of translate.js and the setup below I had no problems compiling my code using Babel.

nvm install node && nvm alias default node && npm update npm -g
npm init --yes
npm install mithril --save
npm install translate.js
npm install webpack --save-dev
npm install --save-dev babel-loader babel-core babel-preset-env --save-dev
npm install --save babel-polyfill
npm install path express --save
npm install body-parser --save
npm install --save @sendgrid/mail

With the setup below I get a script error. Like the one in #47 .
This setup uses the latest Babel version. 7.0 or 7.1.

nvm install node && nvm alias default node && npm update npm -g
npm init --yes
npm install mithril --save
npm install translate.js
npm install path express --save
npm install body-parser --save
npm install --save @sendgrid/mail
npm install webpack webpack-cli --save-dev
npm install --save-dev @babel/core @babel/register @babel/preset-env babel-loader
npm install --save  @babel/polyfill

Am I missing something or could there be a new compile issue using the latest Babel version?

Thanks for all the work on translate.js! Really appreciated!

**Comment by maranomynet** [comment]
So, are you seeing `SCRIPT1002: Syntax error` in Internet Explorer 11?  If not what is the error-message and at which point does it appear (i.e. at runtime in the browser? At build-time? etc..)

Are you using the latest version of translate.js? (check if `npm list translate.js` reports 1.2.5)

How are you loading/importing/linking translate.js into your code/page? (What does that line look like?)

**Comment by Foundasys** [comment]
Yes the error is in IE11.

The error appears not at run time but when it gets loaded in the browser. (IE11)
I need IE11 because of MS Word the desktop version which uses IE11 to display an OfficeJS addin.

The npm list shows I'm using v1.2.5 which I load with "import translate from 'translate.js';". (see screenshot)
I'm using v0.7.0 at the moment which works fine. I know that as of v1.0 your doing thing differently.

Hope this helps a bit!

![image](https://user-images.githubusercontent.com/6333708/49602462-d0dfda80-f988-11e8-82cf-0411f42a0be3.png)

**Comment by maranomynet** [comment]
Thanks. Interesting to see that the bundler seems to ignore `pkg.main` (which points to the IE11 friendly `translate.js/common.js`), but uses instead `translate.js/index.js` which is the es6 module referenced by `pkg.module` but doesn't transpile its contents down to IE11-digestible syntax.

How annoying. I'll investigate.

**Comment by Foundasys** [comment]
`import translate from 'translate.js/common.js';` indeed works fine with v1.2.5 and IE11.

**Comment by maranomynet** [comment]
I haven't had time to look more into this, but the thought occurred to me how strange it seems for a transpiler to support "browserslist" config as transpilation target, but only do so for a subset of the code it processes and completely ignore the rest.

**Comment by maranomynet** [comment]
I just published v1.2.6 which addresses this issue, see [CHANGELOG.md](https://github.com/StephanHoyer/translate.js/blob/master/CHANGELOG.md)
